replicaCount: 1
deploymentName: html-reporting-app
containerName: html-reporting-app
#securityContext:
# allowPrivilegeEscalation: false
#  the docker or the image should have these users or groups setup. #https://stackoverflow.com/questions/53544469/how-to-run-net-core-2-application-in-docker-on-linux-as-non-root/53544813
#or you will keep getting error 137 when the container tries to start.
# runAsUser: 1000
# runAsGroup: 1000
# privileged: false
prometheus:
 scrapping: "'false'"
K8S:
 Type: AKS #  EKS or AKS
resourceLimits:
  memory:
    requests: 500Mi #minimum
    limits: 1000Mi #max
  cpu:
    requests: 250m #minimum
    limits: 250m #max

envVars:
   ARM_CLIENT_ID: "FROMGITSECRETS" 
   ARM_TENANT_ID: "FROMGITSECRETS" 
   ARM_CLIENT_SECRET: "FROMGITSECRETS" 
   ARM_SUBSCRIPTION_ID: "FROMGITSECRETS" 
   K8S_RG_NAME: "RG-PRD-K8S-CLUSTER" # AKS resource group name
   K8S_NAME: "metaks-prd-ae" #AKS NAME
   SA_RG_NAME: "RG-PRD-K8S-CLUSTER"  #storage account's resource group name
   SA_NAME: "azaksmetprdf01" # storage account name
   SLACK_CHANNEL_TOKEN: "FROMGITSECRETS"

image:
  useImagePullSecrets: false
  repository: 'g0pinath/html-reporting-app'
  #also can be accessed via $env:ecr_registry_url if running from pipeline
  pullPolicy: Always
#nodePoolName: smallpool 
nodePoolName: 'app-pool01' # nodeselector
buildID: 'apr2021' #'100' # This is the tag ID for the image. This value will be passed at runtime from the pipeline when helm push
